### ISSUE TITLE
Selectively install apps

### ISSUE THREAD

**Issue by TechMorgan** [PSGitHubUser1/Windows-Essentials-Apps-Installer#6]
### Feature description

I want to select which apps to be installed, and please include these in apps list.
1. Qbittorrent
2. VLC, MPV
3. Visual C++ redistributables
4. DirectX 11
5. Java
6. ffmpeg, if possible include a GUI version.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature <a href='https://github.com/PSGitHubUser1/Windows-Essentials-Apps-Installer/issues' target='_blank'>is not already asked.</a>
- [X] I have checked that this feature is not already implemented

**Comment by PSGitHubUser1** [comment]
Hmmm.. ok

you want only these or the included in repo too?

DirectX 11 wait whaa---??

I prefer you to use 'WingetUI', download it and install any programs you want...

**Comment by varshanreddy** [comment]
> you want only these or the included in repo too?

Yes, these are essential apps for a normal user, so they are needed to be included in the repo.

> DirectX 11 wait whaa---??

It is required for running some games.

**Comment by PSGitHubUser1** [comment]
I just

> > you want only these or the included in repo too?
> 
> Yes, these are essential apps for a normal user, so they are needed to be included in the repo.
> 
> > DirectX 11 wait whaa---??
> 
> It is required for running some games.

I just made this repo for fun... not for a commercial use...  (i mean on huge level)
Better use WingetUI, it looks really good in terms of UI and it supports Scoop, Chocolatey, Winget.. (Npm also i guess..?)..

Please don't make pressure on me.. I just made this for fun..

**Comment by varshanreddy** [comment]
> I just made this repo for fun... not for a commercial use... (i mean on huge level) Better use WingetUI, it looks really good in terms of UI and it supports Scoop, Chocolatey, Winget.. (Npm also i guess..?)..

Yeah, okay

> Please don't make pressure on me.. I just made this for fun..

Ok no problem.


And, what happened to the cursor design repo?

**Comment by PSGitHubUser1** [comment]
> > I just made this repo for fun... not for a commercial use... (i mean on huge level) Better use WingetUI, it looks really good in terms of UI and it supports Scoop, Chocolatey, Winget.. (Npm also i guess..?)..
> 
> Yeah, okay
> 
> > Please don't make pressure on me.. I just made this for fun..
> 
> Ok no problem.
> 
> 
> And, what happened to the cursor design repo?
> 
> 
> 
> 

Well, it was illegal and I knew that someday the author will find it and that's what happened

**Comment by PSGitHubUser1** [comment]
> 2. VLC, MPV 
> 3. Visual C++ redistributables
> 4. DirectX 11
> 5. Java
> 6. ffmpeg

Added these. 

Note: Java with JDK 17, FFmpeg (not sure if its CLI or GUI), DirectX 9/11 idk, Visual C++ 2013, 2015-2019 only, as only they are available on winget.

Added Chocolatey too..
Made many apps' code in comment... which I think is good, like if you want to install an app, just uncomment the code...
containing '::'

**Comment by TechMorgan** [comment]
> Note: Java with JDK 17, FFmpeg (not sure if its CLI or GUI), DirectX 9/11 idk, Visual C++ 2013, 2015-2019 only, as only they are available on winget.

> Added Chocolatey too..
Made many apps' code in comment... which I think is good, like if you want to install an app, just uncomment the code...
containing '::'

Thanks!

**Comment by TechMorgan** [comment]
> > And, what happened to the cursor design repo?
>
> Well, it was illegal and I knew that someday the author will find it and that's what happened

Can you upload it in some other platform like gitlab, gitea?

**Comment by PSGitHubUser1** [comment]
> > > And, what happened to the cursor design repo?
> > 
> > 
> > Well, it was illegal and I knew that someday the author will find it and that's what happened
> 
> Can you upload it in some other platform like gitlab, gitea?

I dont use 'em... because of a silly reason which is... it doesn't have dark mode. Also, I don't understand how to use them....

I have added the apps you wanted except few but it is commented... you can just remove `'::'` these and the code will work. 

1. Download the file
2. Open it in VS Code or your fav code editor
3. Uncomment the code...
4. yes, that's it...

**Comment by PSGitHubUser1** [comment]
> Can you upload it in some other platform like gitlab, gitea?

Oh you mean the cursors... no I can't.
The author (real) found my repo.. and he made a bug report, if he wanted then he could have just reported my account. 

I can't tell you the conversations between him and me. But it made me feel really bad. I knew someday my repo has to be deleted. And thats what happened... that's it
